import React, { useState } from 'react';
import Splash from './pages/Splash';
import Login from './pages/Login';
import ForgotPassword from './pages/ForgotPassword';
import ResetPassword from './pages/ResetPassword';
import ParentRegistration from './pages/ParentRegistration';
import LinkageConfirmation from './pages/LinkageConfirmation';
import RoleSelection from './pages/RoleSelection';
import LegalPolicies from './pages/LegalPolicies';
import SupportDashboard from './pages/SupportDashboard';
import ParentDashboard from './pages/ParentDashboard';
import ChildSwitcher from './pages/ChildSwitcher';
import AttendanceParentView from './pages/AttendanceParentView';
import GradesParentView from './pages/GradesParentView';
import HomeworkParentView from './pages/HomeworkParentView';
import AnnouncementsParentView from './pages/AnnouncementsParentView';
import AnnouncementDetailParentView from './pages/AnnouncementDetailParentView';
import ParentProfile from './pages/ParentProfile';
import NotificationsInbox from './pages/NotificationsInbox';
import TeacherDashboard from './pages/TeacherDashboard';
import TeacherClassSelector from './pages/TeacherClassSelector';
import TeacherAttendanceMarking from './pages/TeacherAttendanceMarking';
import TeacherAttendanceHistory from './pages/TeacherAttendanceHistory';
import TeacherGradeEntry from './pages/TeacherGradeEntry';
import TeacherGradeHistory from './pages/TeacherGradeHistory';
import TeacherHomeworkPosting from './pages/TeacherHomeworkPosting';
import TeacherHomeworkList from './pages/TeacherHomeworkList';
import TeacherAnnouncementPosting from './pages/TeacherAnnouncementPosting';
import TeacherClassRoster from './pages/TeacherClassRoster';
import TeacherProfile from './pages/TeacherProfile';
import AdminDashboard from './pages/AdminDashboard';
import AdminStudentList from './pages/AdminStudentList';
import AdminStudentForm from './pages/AdminStudentForm';
import AdminStudentDetail from './pages/AdminStudentDetail';
import AdminTeacherList from './pages/AdminTeacherList';
import AdminTeacherForm from './pages/AdminTeacherForm';
import AdminTeacherDetail from './pages/AdminTeacherDetail';
import AdminAccountList from './pages/AdminAccountList';
import AdminAccountForm from './pages/AdminAccountForm';
import AdminParentList from './pages/AdminParentList';
import AdminParentDetail from './pages/AdminParentDetail';
import AdminRolesPermissions from './pages/AdminRolesPermissions';
import AdminBulkImport from './pages/AdminBulkImport';
import AdminClassList from './pages/AdminClassList';
import AdminClassForm from './pages/AdminClassForm';
import AdminSubjectList from './pages/AdminSubjectList';
import AdminSubjectForm from './pages/AdminSubjectForm';
import AdminAcademicYear from './pages/AdminAcademicYear';
import AdminTeacherAssignments from './pages/AdminTeacherAssignments';
import AdminAttendanceOversight from './pages/AdminAttendanceOversight';
import AdminGradeOversight from './pages/AdminGradeOversight';
import AdminHomeworkOversight from './pages/AdminHomeworkOversight';
import AdminAnnouncements from './pages/AdminAnnouncements';
import AdminAnnouncementForm from './pages/AdminAnnouncementForm';
import AdminMediaLibrary from './pages/AdminMediaLibrary';
import AdminAttendanceReport from './pages/AdminAttendanceReport';
import AdminGradeReport from './pages/AdminGradeReport';
import AdminPerformanceReport from './pages/AdminPerformanceReport';
import AdminExportCenter from './pages/AdminExportCenter';
import AdminSchoolProfile from './pages/AdminSchoolProfile';
import AdminActivityLog from './pages/AdminActivityLog';
import AdminProfileSecurity from './pages/AdminProfileSecurity';
import AdminHelpSupport from './pages/AdminHelpSupport';
import LoadingState from './pages/LoadingState';
import EmptyState from './pages/EmptyState';
import ErrorState from './pages/ErrorState';
import NoConnectionState from './pages/NoConnectionState';
import AccessDeniedState from './pages/AccessDeniedState';
import LogoutConfirmation from './pages/LogoutConfirmation';
import SessionExpiredState from './pages/SessionExpiredState';
import NotificationSettings from './pages/NotificationSettings';
import Sitemap from './pages/Sitemap';

export default function App() {
    const [route, setRoute] = useState('splash');

    const renderRoute = () => {
        switch (route) {
            case 'splash': return <Splash navigate={setRoute} />;
            case 'login': return <Login navigate={setRoute} />;
            case 'forgot_password': return <ForgotPassword navigate={setRoute} />;
            case 'reset_password': return <ResetPassword navigate={setRoute} />;
            case 'parent_registration': return <ParentRegistration navigate={setRoute} />;
            case 'linkage_confirmation': return <LinkageConfirmation navigate={setRoute} />;
            case 'role_selection': return <RoleSelection navigate={setRoute} />;
            case 'legal': return <LegalPolicies navigate={setRoute} />;
            case 'dashboard': return <SupportDashboard navigate={setRoute} />;
            case 'parent_dashboard': return <ParentDashboard navigate={setRoute} />;
            case 'child_switcher': return <ChildSwitcher navigate={setRoute} />;
            case 'attendance_parent': return <AttendanceParentView navigate={setRoute} />;
            case 'grades_parent': return <GradesParentView navigate={setRoute} />;
            case 'homework_parent': return <HomeworkParentView navigate={setRoute} />;
            case 'announcements_parent': return <AnnouncementsParentView navigate={setRoute} />;
            case 'announcement_detail': return <AnnouncementDetailParentView navigate={setRoute} />;
            case 'parent_profile': return <ParentProfile navigate={setRoute} />;
            case 'notifications_inbox': return <NotificationsInbox navigate={setRoute} />;
            case 'teacher_dashboard': return <TeacherDashboard navigate={setRoute} />;
            case 'teacher_classes': return <TeacherClassSelector navigate={setRoute} />;
            case 'teacher_attendance': return <TeacherAttendanceMarking navigate={setRoute} />;
            case 'teacher_attendance_history': return <TeacherAttendanceHistory navigate={setRoute} />;
            case 'teacher_grades_entry': return <TeacherGradeEntry navigate={setRoute} />;
            case 'teacher_grade_history': return <TeacherGradeHistory navigate={setRoute} />;
            case 'teacher_homework_list': return <TeacherHomeworkList navigate={setRoute} />;
            case 'teacher_homework': return <TeacherHomeworkPosting navigate={setRoute} />;
            case 'teacher_announcement': return <TeacherAnnouncementPosting navigate={setRoute} />;
            case 'teacher_roster': return <TeacherClassRoster navigate={setRoute} />;
            case 'teacher_profile': return <TeacherProfile navigate={setRoute} />;
            case 'admin_dashboard': return <AdminDashboard navigate={setRoute} />;
            case 'admin_students': return <AdminStudentList navigate={setRoute} />;
            case 'admin_student_form': return <AdminStudentForm navigate={setRoute} />;
            case 'admin_student_detail': return <AdminStudentDetail navigate={setRoute} />;
            case 'admin_teachers': return <AdminTeacherList navigate={setRoute} />;
            case 'admin_teacher_form': return <AdminTeacherForm navigate={setRoute} />;
            case 'admin_teacher_detail': return <AdminTeacherDetail navigate={setRoute} />;
            case 'admin_accounts': return <AdminAccountList navigate={setRoute} />;
            case 'admin_account_form': return <AdminAccountForm navigate={setRoute} />;
            case 'admin_parents': return <AdminParentList navigate={setRoute} />;
            case 'admin_parent_detail': return <AdminParentDetail navigate={setRoute} />;
            case 'admin_roles': return <AdminRolesPermissions navigate={setRoute} />;
            case 'admin_bulk_import': return <AdminBulkImport navigate={setRoute} />;
            case 'admin_classes': return <AdminClassList navigate={setRoute} />;
            case 'admin_class_form': return <AdminClassForm navigate={setRoute} />;
            case 'admin_subjects': return <AdminSubjectList navigate={setRoute} />;
            case 'admin_subject_form': return <AdminSubjectForm navigate={setRoute} />;
            case 'admin_academic_year': return <AdminAcademicYear navigate={setRoute} />;
            case 'admin_teacher_assignments': return <AdminTeacherAssignments navigate={setRoute} />;
            case 'admin_attendance_oversight': return <AdminAttendanceOversight navigate={setRoute} />;
            case 'admin_grade_oversight': return <AdminGradeOversight navigate={setRoute} />;
            case 'admin_homework_oversight': return <AdminHomeworkOversight navigate={setRoute} />;
            case 'admin_announcements': return <AdminAnnouncements navigate={setRoute} />;
            case 'admin_announcement_form': return <AdminAnnouncementForm navigate={setRoute} />;
            case 'admin_media_library': return <AdminMediaLibrary navigate={setRoute} />;
            case 'admin_attendance_report': return <AdminAttendanceReport navigate={setRoute} />;
            case 'admin_grade_report': return <AdminGradeReport navigate={setRoute} />;
            case 'admin_performance_report': return <AdminPerformanceReport navigate={setRoute} />;
            case 'admin_export_center': return <AdminExportCenter navigate={setRoute} />;
            case 'admin_school_profile': return <AdminSchoolProfile navigate={setRoute} />;
            case 'admin_activity_log': return <AdminActivityLog navigate={setRoute} />;
            case 'admin_profile_security': return <AdminProfileSecurity navigate={setRoute} />;
            case 'admin_help_support': return <AdminHelpSupport navigate={setRoute} />;
            case 'loading_state': return <LoadingState navigate={setRoute} />;
            case 'empty_state': return <EmptyState navigate={setRoute} />;
            case 'error_state': return <ErrorState navigate={setRoute} />;
            case 'no_connection_state': return <NoConnectionState navigate={setRoute} />;
            case 'access_denied_state': return <AccessDeniedState navigate={setRoute} />;
            case 'logout_confirmation': return <LogoutConfirmation navigate={setRoute} />;
            case 'session_expired_state': return <SessionExpiredState navigate={setRoute} />;
            case 'notification_settings': return <NotificationSettings navigate={setRoute} />;
            case 'sitemap': return <Sitemap navigate={setRoute} />;
            default: return <Splash navigate={setRoute} />;
        }
    };

    return renderRoute();
}
